- name: Install docker apt key
  apt_key: keyserver=https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88 state=present

- name: Install docker apt repository
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/{{ apt_distribution }} {{ ansible_distribution_release }} stable" state=present

- name: Install dmsetup
  apt: pkg=dmsetup state=present
  register: dmsetup_result
  when: docker_config['storage-driver'] == "devicemapper"

- name: Run dmsetup mknodes
  command: dmsetup mknodes
  when: dmsetup_result.changed

- name: Unhold docker package
  shell: apt-mark unhold docker-ce
  when: docker_version != "latest"

- name: Install docker
  apt: name=docker-ce{% if docker_version != "latest" %}={{ docker_version }}-0~{{ apt_distribution }}-{{ ansible_distribution_release }}{% endif %} state=present

- name: Hold docker package
  shell: apt-mark hold docker-ce
  when: docker_version != "latest"

- name: Install python docker package
  pip: name=docker

- name: Install docker-compose package
  pip: name=docker-compose state={% if docker_compose %}latest{% else %}absent{% endif %}
