---

- name: "Remove deprecated docker package"
  apt: name=lxc-docker state=absent

- name: "Remove deprecated docker apt repository"
  apt_repository: repo="deb https://get.docker.com/ubuntu docker main" state=absent update_cache=no

- name: "Remove deprecated docker apt key"
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=absent

- name: "Install docker apt key"
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: "Install docker apt repository"
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main" state=present

- name: "Install docker package"
  apt: name=docker-engine state=present

- name: "Install pip package"
  apt: name=python-pip state=present

- name: "Install python docker package"
  pip: name=docker-py

- name: "Install docker-compose package"
  pip: name=docker-compose

- name: "Ensure docker is started at boot"
  service: name=docker enabled=yes

- name: "Configure docker host"
  lineinfile: >
    dest=/etc/default/docker
    state=present
    regexp='^#?DOCKER_OPTS='
    line='DOCKER_OPTS="{{ docker_options }}"'
  when: docker_options is defined
  notify: restart docker
