- name: Restart docker
  service: name=docker state=restarted

- name: Restart ufw
  service: name=ufw state=restarted

- name: Reload systemd daemon
  systemd: name=docker state=restarted daemon_reload=yes
